### ISSUE TITLE
[urgent] coverage report still missing for balsamic --> scout uploads

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#1008]
Coverage report for this case is missing: https://scout.scilifelab.se/cust087/F0037994-2 case name: petrobin

Coverage report exists and generated correctly: 
```
$ls /home/proj/production/cancer/cases/petrobin/analysis/delivery_report
petrobin_delivery_ready.hk  petrobin.hk  petrobin.hk.yaml  petrobin_qc_report.html  petrobin_report.html
```

@Mropat @moonso any idea what is going on?

**Comment by Mropat** [comment]
This issue is happening because a new version of Hermes was not deployed in production when the feature was introduced.
I have re-uploaded the case to scout for petrobin in particular.

To resolve for cases analyzed <45 days ago:

- run `cg workflow balsamic config-case <case_id>`
- run` cg workflow balsamic store <case_id>`
- run `cg upload scout <case_id> --re-upload`

The case should be updated

For cases analyzed  >45 days ago:
- run `cg workflow balsamic start <case_id>`

Case should be updated within 24h
