### ISSUE TITLE
Fallback for SARSCoV-2 orders when ticket system is unresponsive

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/cg#1264]
## Description
Sometimes when creating new orders in the orderportal the ticket system is unresponsive and cg ends up with a situation where it doesn't know the ticket-number for the new order. When it then tries to create a case using the ticketnumber as name it crashes: 
```            
            for sample_data in samples:
                case_obj = self.status.find_family(customer=customer_obj, name=ticket)

                if not case_obj:
                    case_obj = self.status.add_case(
                        data_analysis=data_analysis,
                        data_delivery=data_delivery,
                        name=ticket,
                        panels=None,
                    )
               ...
```

## Suggested solution
- Fail when we don't get a ticket number from OsTicket

## This can be closed when
- [ ] The order can be placed and ticket ends up empty

**Comment by Mropat** [comment]
@patrikgrenfeldt  is this finished?
If not, needs help placing the priority within the coming quarter from @henrikstranneheim

**Comment by patrikgrenfeldt** [comment]
No fallback has been implemented

**Comment by henrikstranneheim** [comment]
Action:
- Ask Anna G:
- How this situation is discovered today and how it is solved manually
- How often does this happen?
- What is worst:
  -  Having  entries into LIMS and StatusDB which lacks a ticket number
or
  - Having a ticket in Susy with no data in LIMS and StatusDB


Possible solution:
We should try and catch the ticket_number returned from the ticketing system Susy and then notify the customer in the order portal that there was an issue creating the ticket due to lack of response from Susy. We should extend the error message to be more specific.

```
try:
            ticket_nr: Optional[int] = self.osticket.open_ticket(
                name=user_name,
                email=user_mail,
                subject=order.name,
                message=message,
            )

            LOG.info(f"{ticket_nr}: opened new ticket")
        except TicketCreationError as error:
            LOG.warning(error.message)
```

**Comment by Vince-janv** [comment]
@annagellerbring @AnnaZetterlund. This should now be fixed. A ticket will still be created, but no order will be placed. The customer will get an error message, and will have to submit the order again.
