### ISSUE TITLE
Define the analyses to be delivered according to BALSAMIC tags

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#1389]
## Description

Currently, BALSAMIC delivery can be done using three different flags: `balsamic`,` balsamic-analysis` and `balsamic-qc`. However, the files to be delivered are not clearly defined.

Therefore, and taking into account the analysis output files generated (https://github.com/Clinical-Genomics/hermes/issues/44), it would be convenient to discuss and create new tags (if necessary) based on the well-defined customer's requirements.

## This can be closed when:

- [x] A catalog of output analysis files offered to clients has been defined. **See following [issue](https://github.com/Clinical-Genomics/hermes/issues/44).** 
- [x] The expected output has been associated to the different flags in CG.  **Only one tag will be used, see comment below.**
- [x] The used tags and their associated files have been defined. **Only one tag will be used, see comment below.**
- [x] The analysis files are successfully uploaded and delivered. @ivadym @keyvanelhami  we can check this when deployed

**Comment by keyvanelhami** [comment]
This issue is related to [this issue](https://github.com/Clinical-Genomics/hermes/issues/44) where the files today are delivered, and what files that we would like to start/stop deliver are summarized. 

**My suggestions:**
Remove `balsamic-qc` and `balsamic-analysis` and only use `balsamic` flag to deliver everything as suggested [ in this here](https://github.com/Clinical-Genomics/hermes/issues/44). The reason why we had the different flags, was because we where delivering big files like bam and concat fastq-files. These files are no longer being delivered and the `-d balsamic` will be enough.

**Comment by ashwini06** [comment]
@ivadym : will be implementing the changes in cg for `cg deliver -d balsamic`, while validation for v9.0 is ongoing

**Comment by ivadym** [comment]
Closed via https://github.com/Clinical-Genomics/cg/pull/1477.
