### ISSUE TITLE
Fix code scanning alert - I/O function calls should not be vulnerable to path injection attacks

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#1425]
Tracking issue for:
- [ ] https://github.com/Clinical-Genomics/cg/security/code-scanning/1

**Comment by thelander** [comment]
This endpoint doesn't seem to be used anywhere (yet? anymore?). 
https://github.com/Clinical-Genomics/cg/blob/034af04bdcda4fc529244de4b17fde6308f5001f/cg/server/invoices/views.py#L196

Can it be deleted altogether, or am I missing something? 😊 Otherwise it could probably be fixed by validating `cost_center` against `KTH` or `KI`.

**Comment by Mropat** [comment]
Cannot be deleted, it is being used in invoicing
Validation against KI and KTH would do the trick!
