### ISSUE TITLE
Corrupted fastq files

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/cg#1551]
Balsamic recently started to get error related to the integrity of input fastq, see for example (`/home/proj/production/cancer/cases/politedory/logs/BALSAMIC.politedory.fastp_umi.17.sh_3468832.err`):
```
fastp --thread 8 --in1 /home/proj/production/cancer/cases/politedory/analysis/fastq/concatenated_ACC10056A3_XXXXXX_R_1.fastq.gz --in2 /home/proj/production/cancer/cases/politedory/analysis/fastq/concatenated_ACC10056A3_XXXXXX_R_2.fastq.gz --out1 /home/proj/production/cancer/cases/politedory/analysis/fastq/concatenated_ACC10056A3_XXXXXX_R_1.umi_optimized.fastq.gz --out2 /home/proj/production/cancer/cases/politedory/analysis/fastq/concatenated_ACC10056A3_XXXXXX_R_2.umi_optimized.fastq.gz --json /home/proj/production/cancer/cases/politedory/analysis/qc/fastp/concatenated_ACC10056A3_XXXXXX_R_fastp_umi.json --html /home/proj/production/cancer/cases/politedory/analysis/qc/fastp/concatenated_ACC10056A3_XXXXXX_R_fastp_umi.html --overrepresentation_analysis --trim_tail1 1 --n_base_limit 50 --length_required 25 --low_complexity_filter --trim_poly_g --detect_adapter_for_pe;
        
Activating singularity image /home/proj/production/cancer/balsamic_cache/10.0.2/containers/align_qc.sif
Detecting adapter sequence for read1...
No adapter detected for read1

Detecting adapter sequence for read2...
No adapter detected for read2

ERROR: igzip: invalid gzip header found
[Thu Jul 28 22:18:18 2022]
Error in rule fastp_umi:
    jobid: 0
    output: /home/proj/production/cancer/cases/politedory/analysis/fastq/concatenated_ACC10056A3_XXXXXX_R_1.umi_optimized.fastq.gz, /home/proj/production/cancer/cases/politedory/analysis/fastq/concatenated_ACC10056A3_XXXXXX_R_2.umi_optimized.fastq.gz, /home/proj/production/cancer/cases/politedory/analysis/qc/fastp/concatenated_ACC10056A3_XXXXXX_R_fastp_umi.json, /home/proj/production/cancer/cases/politedory/analysis/qc/fastp/concatenated_ACC10056A3_XXXXXX_R_fastp_umi.html
```

Cases where errors are related to the integrity of the `fastq.gz` files (error inte steps `fastp_umi` or `fastqc`):
politedory (TN, WGS)
lovedjaguar (TO, PANEL, SWEP53cfDNA)
normalshiner (TO, PANEL, SWEP53cfDNA)
fancybat (TO, PANEL, SWEP53cfDNA)
acebunny (TO, PANEL, SWEP53cfDNA)

This issue can be closed when the error related to invalid gzip header no longer happen

**Comment by rannick** [comment]
The issue manifests in 2 ways:

**Fastqc error** when unexpected EOF in concatenated fastq
Failed to process filename
java.io.EOFException
        at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:269)

**Fastp(_umi) error** when unexpected EOF in concatenated fastq
ERROR: igzip: Error invalid gzip header found: filename

But the origin is always that the concatenation got interrupted. It happens when the login node is overloaded (when start_available is executed). I see 2 possible fixes:
1) Throw an error if concatenation is not finished, so BALSAMIC is not started, but that is a minimal difference as the crash would anyway happen a step further
2a) Send the concatenation job to SLURM so there is no competition with other jobs on the login node
2b) Use BALSAMIC to concatenate -> SLURM would be used

**Comment by rannick** [comment]
DECISION: Move concatenation to BALSAMIC: https://github.com/Clinical-Genomics/BALSAMIC/issues/993
