### ISSUE TITLE
Case directories of failed re-run BALSAMIC cases are removed

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#1574]
## Description

If a re-run case fails in BALSAMIC the case directory gets removed. This happened for re-runs that didn't have a `Cleaned At` date set. It seems that these old cases without `cleaned at` date are continuously prone to be cleaned as part of the logic used in `analyses_to_clean`, although the cleaning doesn't actually happen since there is no folder to be cleaned. This is not the case anymore after the case is re-run and the action is no longer set as `running`.

## Suggested solution

Several things could be potentially done:
 - Add a `Cleaned At` date to old cases lacking one
 - Modify the logic in `analyses_to_clean` to consider re-run cases. For example, check if the analysis has a corresponding re-run and skip it if so.

## This can be closed when

Re-run cases are properly cleaned

**Comment by karlnyr** [comment]
So, using an example `handycalf` . Looking into the clean logs the case was marked for cleaning since it's first delivery in 2021. However, for unknown reasons the directory could not be removed. I am assuming that the directory could have been manually removed prior to the script running. This would result in the `cleaned_at` column on `Analysis` to be empty and thats why it was marked for removal but never deleted because there was nothing to delete. 

Looking at the function controlling the removal of analysis dirs:

https://github.com/Clinical-Genomics/cg/blob/5c9d2a46da28c4845b088592d9bf0b16745dfe53/cg/cli/workflow/commands.py#L186

and:

https://github.com/Clinical-Genomics/cg/blob/5c9d2a46da28c4845b088592d9bf0b16745dfe53/cg/cli/workflow/commands.py#L152

Neither of these are handling the Error properly, and one solution could be handling already removed directories by setting the `cleaned_at` date to now.

**Comment by henrikstranneheim** [comment]
- Add a case path exists check and an exception. Set cleaned_at in statusdb

**Comment by henrikstranneheim** [comment]
I think this was fixed by @GustavLagneborgScilifelab in https://github.com/Clinical-Genomics/cg/pull/1577. Reopen if I am incorrect
