### ISSUE TITLE
Panel to add to the CLinical Master List

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/cg#1620]
could you add the panels: 

1. Retinal Distrofy
2. Hearing impairment and deafness
3.  Ciliopathy
4. Hydropspanel

to the Clinical master list?

Thank!

**Comment by 4WGH** [comment]
ok thanks, last time it was Chiare who fixed this so I thought was better to ask here.
how can I follow the issue now? do you have a ticket number ?

**Comment by 4WGH** [comment]
Maybe I should add that the panels are already in SCout and ordered by cLinGenent but not avaialbe at the case level as not belonging to the CLinical Master list :)

**Comment by dnil** [comment]
Hi @4WGH! The master list is a functionality of CG. I assume you have asked the other groups that use the same list that they concur? I think they do either way… 😊 

You can follow the issue here, on GitHub. If you want a ticket, which may be the more common  solution for this kind of task, please use the support system! But it’s perfectly fine this way too - we just move it around, or maybe even fix it.

**Comment by dnil** [comment]
Hi @4WGH - should be done now: new cases or cases fully rerun from now on that include panels on the master list will get the updated master list.

**Comment by 4WGH** [comment]
thanks!
will check next week on new cases 🙂


Michela

________________________________
Från: Daniel Nilsson ***@***.***>
Skickat: den 11 november 2022 13:27
Till: Clinical-Genomics/cg ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/cg] Panel to add to the CLinical Master List (Issue #1620)


Hi @4WGH<https://github.com/4WGH> - should be done now: new cases or cases fully rerun from now on that include panels on the master list will get the updated master list.
