### ISSUE TITLE
Ability to specify DNA-case when uploading rna-to-scout

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/cg#1712]
## Description

When trying to upload mip-RNA reports to mip-DNA sample with multiple entries in the database (example: ) the `cg upload rna-to-scout` looks for all available and picks one. This can cause issues when needing to upload to a specific DNA-sample-case when it is not automatically picked. 

Currently the only fix is to:
1. Manually remove sample relations in statusDB to the case that should not be picked during the upload
2. Upload rna-to-scout
3. Re-enter removed sample relationships

## Suggested solution

Add a dna-case flag to: `cg upload rna-to-scout`

relevant files:
cg/cli/upload/scout.py
cg/meta/upload/scout/uploadscoutapi.py

## This can be closed when

When a dna-case flag is added to `cg upload rna-to-scout`

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by peterpru** [comment]
The way the RNA upload commands are intended to run is that they check how many DNA samples are connected by subject_id, and if it is not exactly 1, it should return an error, and inform you how many samples are connected. It should not be able to just pick one. Would you have an example of this bug? (screenshot or name of a case I could check in stage)

In atlas you can find specific commands for uploading RNA results to a specific case and DNA sample, this way you can upload without having to change anything in statusDB: https://atlas.scilifelab.se/production/data_analysis/workflows/MIP_analysis/#uploading-rna-results-to-scout.

Example: first get the file path of the RNA file to upload:
`housekeeper get file -V --tag junction --tag bed <rna_case_id>`

Secondly: Upload this RNA file to the DNA case and sample you want:
`scout update individual -c <case_id> -n <customer_sample_id> splice_junctions_bed <path/to/junction_file.bed>`

Note: fusion reports are uploaded on the case level, bed and bigwig files are on the sample level.

**Comment by ChrOertlin** [comment]
Hi,

the RNA sample that I was working on was related to this DNA sample: 15067-II-2U
When searching in statusDB it will show you the RNA sample we wanted to upload (ACC11022A6). The following DNA samples are available for this: ADM1524A35 (cutegopher) and ADM1138A9 (vocalwhale).

When running the cg upload rna-to-scout command:
`cg upload rna-to-scout [--research] [--update-fusion-report] [--dry-run] <rna_case_id>`
 the upload was automatically picking vocalwhale for upload. However, the upload to cutegopher was wanted. 



To resolve this @gustavlagneborg and I needed to manipulate statusDB by temporarily removing the relationship between the vocalwhale and our RNA-sample.

It seems this is an issue that happens more frequently according to @gustavlagneborg. I think @Karl-Svard  might have also some input here.

Therefore, specifying which DNA case an RNA sample has to be uploaded to might be helpful in the future. 


I hope the example makes it a bit clearer.

**Comment by Karl-Svard** [comment]
@ChrOertlin wasn't the issue that the DNA sample was involved in a re-run, so we had the two cases **cutegopher** and **vocalwhale** to pick from. Where we wanted it to upload to the most recent one (cutegopher) but it instead chose the other one. We never had two separate DNA samples connected to this RNA one.

**Comment by ChrOertlin** [comment]
Indeed it was the same DNA sample (15067-II-2U) with multiple DNA case entries (cutegopher and vocalwhale)

**Comment by ChrOertlin** [comment]
Here is another case:

RNAcase: equalbunny (mip-rna)

subject id:
GMSB-UP046

linked DNA cases:
keenslug (balsamic) <-- get picked for upload
proudhawk (mip-dna) <-- needs to be uploaded here

Solution for me would be to alter statusDB, which in this case is super messy as the subject ID hast two different sample names under keenslug. 

Is there another way that I am not aware of?

**Comment by peterpru** [comment]
RNA uploads can be very tricky indeed.

You can upload cases without altering statusDB by using the upload commands stated in atlas. These are the commands I posted higher up in these comments. I am happy to take a zoom call to show them in-depth.

To clarify why this upload command is not working for equalbunny. This is because of the way cg handles the uploads. It will match by customer ID, it will match by subject_id, but it will not match by tumour state. The RNA sample is marked as tumour, the balsamic sample is marked as tumour, but the mip-DNA sample is not marked as tumour. It will not upload a tumour sample to a non-tumour sample.

The idea behind this is that cases can come as a tumour/non-tumour pair, and then we want the tumour RNA associated to the tumour DNA, and not to the normal sample.

If this mip-DNA sample is a tumour sample, you can change it to a tumour sample, and equalbunny will then upload to both cases, or you can use the manual commands to target a specific sample. I hope this makes it more clear.

**Comment by peterpru** [comment]
I took some time to check out the first case you mentioned. What happened here is that the sample ADM1138A9 from case vocalwhale did not have its subject_id filled in. If this is from the same subject, and the id was filled in, the upload command you mentioned would have uploaded to both vocalwhale and cutegopher.

As for the reasons why this is not filled in, this can be due to the customer not filling in this field when ordering the case, or when it is very old samples.
