### ISSUE TITLE
Suggestion for improvement: Include test after changes to code configuration.

### ISSUE THREAD

**Issue by AnnaLeinfelt** [Clinical-Genomics/cg#1758]
## Description

 - When changes to code used for configuration files maybe a test should include to try to start a new analysis.

This was suggested as an action in https://github.com/Clinical-Genomics/Deviations/issues/409

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
I think the instructions are clear enough and a test is the current best practice which is usually followed very strictly. I think this particular case was human error missing the “unexpected” change of how the code was interpreted when executing. Hence, no test was performed since there was not any expectation of a difference. I do not see any systematic errors in this process nor any need to change instructions. I think we can close this.
