### ISSUE TITLE
Not possible to delete application tags/versions from database

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#1913]
## Description

When trying to delete either an application tag or application version from the database, the following error occurs:

![image](https://user-images.githubusercontent.com/19325955/231458292-82e4b43b-3b8e-40b7-807e-4adabc063e07.png)

![image](https://user-images.githubusercontent.com/19325955/231458330-088fb92e-ef77-4bdf-a5af-f1c47acac060.png)

Additionally, when creating a new apptag, the version associated with it has to be created based on an already existent apptag (which explains the nonsensical values set for the test application version above).

## Suggested solution

- Needs refinement.

## This can be closed when

- It is possible to delete an application tag/version from the database.

## Blocked by

- Nothing.

**Comment by henrikstranneheim** [comment]
- I think that you can not remove `Application` since: `application id` in `Application versions` cannot be null (must exist)
- You can not remove `Application versions` unless you remove all samples with the `application_version_id` since it cannot be null.


<img width="1193" alt="Screenshot 2023-04-12 at 15 51 05" src="https://user-images.githubusercontent.com/584738/231478821-da0fdb58-30a6-458a-a020-94ab4ac97e4b.png">

**Comment by beatrizsavinhas** [comment]
I realised the problem here was actually in the instructions to create a new apptag - it said "Field: Version: Use 1" and doing that in the GUI would lead to a previous apptag version being overwritten with the version created for the new apptag.
@Vince-janv has removed this option from the GUI to prevent this https://github.com/Clinical-Genomics/cg/pull/1904#issuecomment-1506483947
The instructions will be updated at https://github.com/Clinical-Genomics/atlas/pull/1624#pullrequestreview-1383388765
