### ISSUE TITLE
Allow scout loading of STR VCFs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#201]
Short tandem nucleotide repeats can expand to cause genetic disease. ExpansionHunter can detect targeted STRs from bam files and generate VCFs. Scout can display these.

Problem: 
MIP generates STR VCFs with ExpansionHunter: [#252](https://github.com/Clinical-Genomics/MIP/issues/252)
Recorded in qc_sampleinfo.yaml:
```
[FAMILY_ID]:
  expansionhunter:
    Path: [path/file.vcf]
```
Sample info key for ExpansionHunter VCF to enter scout case load config:
[#787](https://github.com/Clinical-Genomics/scout/issues/787) [#968](https://github.com/Clinical-Genomics/scout/pull/968) 
```
family: '643594'
...
vcf_str: scout/demo/643594.clinical.str.vcf.gz
```

Suggested solution:
- [x] store VCF STR to HK. Tag it with 'expansion hunter vcf'
- [x] add to the scout upload config: `vcf_str`

To do:
- Fix unit tests (TB and cg)
- Testing PR

Q: How to view in Scout?
A: Ask DN, MM and CR, action EOL

DoD:
 - Viewable in Scout

**Comment by emiliaol** [comment]
mip 7

**Comment by barrystokman** [comment]
@henrikstranneheim @jemten 

Trailblazer is parsing <case_id>_qc_sample_info.yaml, and is expecting a key `program` in that file. The MIP7.1 sample info file I'm using (justhusky) does not have that key. Before I start changing things in TB, is that intentional?

Example: TB is trying to get the path below (example from MIP6) but throws a KeyError for key `program` for MIP7.1

```
program:
  ...
  svdb:
    path: /home/proj/stage/rare-disease/cases/grownliger/analysis/grownliger/bwa/grownliger_sorted_md_brecal_comb_SV.vcf
```

**Comment by henrikstranneheim** [comment]
Yes, it is intentional. We have replaced “program” with “recipe” as it is a better description of the actual code. 

I know this yaml is a bit complex, but it is hard to represent all this information in a simple manner. You can perhaps be a little wiser by looking at the description of the file here: https://github.com/Clinical-Genomics/MIP/blob/master/documentation/API/Sample_info.md. It would be great to sit together for this one to explain. However, I guess mail will have to do for now. Please, Let me know if you have more questions.

**Comment by barrystokman** [comment]
Last atsk: fix unit tests
