### ISSUE TITLE
String type (quoted) semantic version numbers passed to Scout

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#213]
Contact person: Daniel Nilsson

Semantic version numbers should be string type (quoted) in yaml to allow automagick parsing.

Problem: 
Rank model shows wrong version in Scout [#961](https://github.com/Clinical-Genomics/scout/issues/961)

Expected outcome / suggested solution:
Scout load config yamls should recieve quoted version numbers (e.g. rank models).

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

**Comment by patrikgrenfeldt** [comment]
If one runs the command `cg upload scout --print [family_id]` for any recently uploaded analysis one can see the data that is passed to scout and that it has quotations, i.e. `'rank_model_version': '1.20'`. Looking at the same case in scout gives `Rank model Version 1.2` This issue seems to be somewhere downstream of cg, closing the issue here.
