### ISSUE TITLE
Fix Loqusdb somatic database uploads

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/cg#2211]
## Description

TNscope VCF is missing GQ-values. Therefore, SNVs are not being uploaded to the `loqusdb-somatic` database. 

It has been solved in Loqusdb side in https://github.com/Clinical-Genomics/loqusdb/pull/118.

## Suggested solution

Adapt CG to allow QUAL filtering in Loqusdb uploads. 

## This can be closed when
- [x] Fix: SNVs are being uploaded to `loqusdb-somatic`. https://github.com/Clinical-Genomics/cg/pull/2297
- [x] Wipe `loqusdb-tumor` and `loqusdb-somatic` databases
- [x] Remove Loqusdb IDs from StatusDB cancer samples
- [x] The incorrectly uploaded cases have been reuploaded.

---

## Current context

Somatic variants uploaded (`loqusdb-somatic`):
- `SNV` (`vcf-snv` tag): `tnscope.vcf.gz` file
- `SV` (`vcf-sv` tag): `svdb.vcf.gz` file

Tumor variants uploaded (loqusdb-tumor):
- SNV (`vcf-snv-germline-tumor` tag): `tumor.dnascope.vcf.gz` file
- SV: None

---

## Proposed uploads

Upload only WGS tumor-normal cases:

Somatic variants uploaded (`loqusdb-somatic`):
- `SNV` (`vcf-snv-clinical` tag): `.tnscope.clinical.filtered.pass.vcf.gz` file
- `SV` (`vcf-sv-clinical` tag): `.svdb.clinical.filtered.pass.vcf.gz` file

Tumor variants uploaded (loqusdb-tumor):
- SNV (`vcf-snv-germline-tumor` tag): `tumor.dnascope.vcf.gz` file (from WGS tumor-only and tumor-normal cases)
- SV: (`vcf-sv-germline-tumor` tag): `tumor.manta_germline.vcf.gz` file (from only WGS tumor-normal cases)

**Comment by ivadym** [comment]
Adding some QUAL scores here from the cases we tried to upload to Loqusdb:

<details>
<summary>SNVs</summary>
<img width="888" alt="Screenshot 2023-08-04 at 18 10 07" src="https://github.com/Clinical-Genomics/cg/assets/26309194/d15eedf9-1b24-415b-b6db-9a98eef07b78">
</details>

<details>
<summary>SVs</summary>
<img width="888" alt="Screenshot 2023-08-04 at 18 17 18" src="https://github.com/Clinical-Genomics/cg/assets/26309194/d394e6aa-3492-436e-bee6-a657989bc731">
</details>

<details>
<summary>Germline SNVs</summary>
</details>


<details>
<summary>Germline SVs</summary>
<img width="888" alt="Screenshot 2023-08-04 at 18 19 58" src="https://github.com/Clinical-Genomics/cg/assets/26309194/474521d8-ead1-497b-8d0a-c4930738de2b">
</details>

**Comment by mathiasbio** [comment]
I spent a little time thinking about this after the refinement-meeting. My initial question then was if it would be better to upload less filtered variants to the database, to have a larger set of artefacts to annotate and potentially filter with.

But the way it was explained to me during the meeting, was that the purpose of this database was not to annotate artefact frequencies for the purpose of filtering out these artefacts, but to build a database of true somatic variants, with the ultimate purpose being (I might have misunderstood this) to help the clinician -- when faced with a variant of interest -- to be more certain that the variant is a true somatic variant.

I'm still confused about this though. There are 2 ways I can imagine using this database to help the clinician in this case. For instance the variant has been annotated with a frequency of around 2%, what could this mean:
1. Regardless of the tumor + normal filtering, and extra filters we apply, some common artefacts still slips into the database. This variant is such an artefact and the clinician should disregard it.
2. This is a common cancer-relevant mutation and the clinician should not filter it out. But in this case, I wonder if our database has been helpful at all, since if it is such a common cancer-relevant mutation, it should already be well known to the clinicians and be present in some other database.

If I were to guess, I would think that the main use of this database for helping the clinician determine when faced with a variant of interest, if it is a true somatic variant or not, will be mainly derived from seeing that the variant:
1.  has a high frequency in this database we're building, but it is not existing in any literature -- and consequently they might suspect that it is an artefact. 
2. it does not exist in our database at all, which makes it less likely to be an artefact, and more likely to be a true somatic variant. Now if we're not using a normal to filter in this particular case, it might still be a germline variant. Especially if it has a frequency between 0.3 - 0.7 or around 1.0 we would be right to suspect so, but even in this case I don't see how the database would help the clinician determine if this variant is a germline or somatic variant, because again, if we see that this variant has been seen in 5% of the database, the question is still open if it's a common cancer mutation or an artefact.

In the end, I'm not sure I have any objection to this database being built on these filtered VCFs though, except that if the main purpose of the database will be as I suspect, to help decide if the variant is an artefact or not, then a database built based on these VCFs might be less useful for this.

There's a current perspective and a future perspective for this.

For the current perspective I'm worried that:
1. particular artefacts that may often have a high allele-frequency would be filtered out in these T+N VCFs and be almost missing in the database, and won't be available for the tumor only analyses. 
2. we might still based on randomness of the effectiveness of our filters put recurring artefacts into the database, which appears in 10 out of 100 cases, only in 1 out of 100 of these cases in those few times it slips by, and could make it more difficult to filter them out, once they appear. 

For the future perspective I'm thinking if we change our filtering approaches, then most of the artefact variants that were previously filtered out on our hard quality cut-offs, and were not added to the database will have no ability to be filtered out with the database since they were never added. 

These are my thoughts at the moment and I could be completely wrong. And I still think it could be nice for us to try to build a database of true somatic variants, but I imagine we wouldn't get much use from it until we have a looot of cancer cases in it, I mean if the purpose would be to find neeew cancer-relevant mutations that have not been described and added to external databases before. Lots of text... 😬

**Comment by ivadym** [comment]
Decision:
- Re-upload of all the original cases 
- No QUAL threshold for somatic database
- Start uploading germline SVs, `manta` (only tumor-normal)

**Comment by ivadym** [comment]
Cases reuploaded to Loqusdb following the proposed solution. Closing!
