### ISSUE TITLE
Copy sample sheet when the flow cell is created in demultiplexed-runs 

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2263]
## Description
Currently, we copy the sample sheet separately from the run directory into the demultiplexed-runs directory for a flow cell when it is post processed. This adds extra complexity to the post processing and makes testing trickier.

## Suggested solution
Copy the sample sheet with the other files from the start when the flow cell is created in the demultiplexed-runs directory.

This will let us remove some complexity from the post processing flow and the test fixtures.

## This can be closed when
The step where we copy the sample sheet is no longer required in post processing.

## Blocked by
Refinement needed:

- Is there any reason why this is done as a separate step in the post processing flow?
- Can the sample sheet be outdated somehow?

**Comment by ChrOertlin** [comment]
Continuation of #2246

There is a comment in the code from a meeting where we mentioned moving the sample sheets might not be needed anymore in the new workflow. 

@karlnyr , @henrikstranneheim  We should decide on how to handle sample sheet in the new demux workflow. 

## What makes them?

Sample Sheets exists prior to the demultiplexing calls, since demultiplexing requires knowledge on samples and indeces that are present on a flow cell. 

the BCL CONVERT software looks in the root bcl-input folder for a sample sheet, which in this case would be 
``` ./flow-cells/novaseq/runs/flowcellA```


The demultiplexing of Novaseq flow cells creates a sample sheet in the target directory in the Reports folder. 
This would make the copying of the sample sheet for demultiplexing with BCL convert obsolete.
However, for now initiating a FlowCellDirectoryData object requires a Sample sheet in the demux-runs parent folder.

## Where should they go?

Currently, the model FlowCellDirectoryData has a hard coded path to sample sheets under its root e.g. ```./demultiplexed-runs/flow-cell-A/SampleSheet.csv```

## Future

Have logic to fetch any sample sheets in the demultiplex-runs folder

**Comment by karlnyr** [comment]
I think there was some kind of logic to have the sample sheet in the directory of interest because we were manually interacting with it. If we instead treat the demultiplexing as the analysis, perhaps it would make more sense to not move the sample sheet at all? 

When we start, how about that we check if there is a sample sheet in housekeeper. If it exists, fetch it, if not we create one and store it. Then we can assume in post processing that we should have a samplesheet in housekeeper? Or does this create to much dependency?

**Comment by seallard** [comment]
The sample sheet is now stored in housekeeper when it is created and fetched from there subsequently.
