### ISSUE TITLE
Add `cg downsample` subcommand

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2278]
## Description

Add `cg downsample` subcommand that performs all steps required for downsampling an existing sample via cg.
- Start with `cg downsample sample`
- Once implemented, add `cg downsample case` that links over the samples  (note: for cases with several linked samples we might want to include the possibility to downsample different number of reads for different apptags)

Required parameters:
- sample_id: sample_id
- read-number or read-pairs-number : amount of reads to subsample

Optional:
- sample_name: name to give to subsample sample. If not given it should be created based on the original name or id + a suffix with the number of reads (e.g. *-75M)
- customer

Steps to perform:

1. Check if fastq are decompress. If not:
- Decompress samples: `cg decompress sample $sample_id`
- Store samples: `cg store sample $sample_id`
2. Get fastq file directory
3. Subsample: `sbatch --mem 100GB -n 2 -t 04:00:00 -A production -e $run_directory/down-%j.err -o $run_directory/down-%j.log /PATH2/downsample.sh $in_fastq_directory $run_directory $number_reads_to_downsample $total_reads`
4. Tracking in trailblazer status and kick after completion
5. Create the new sample adding the downsample information
- `cg add sample -d $number_reads_to_downsample -s $status -a  $apptag $customer  $down_sample_id`
- `cg set sample --skip-lims -y -kv from_sample $sample_id $down_sample_id`
- number of reads should also be updated in statusdb
6. Store in housekeeper
- `housekeeper add bundle $down_sample_id`
- `housekeeper include $down_sample_id`
- `housekeeper add file -b $down_sample_id -t fastq $down_fastq_r1`
- `housekeeper add file -b $down_sample_id -t fastq $down_fastq_r2`
7. Print new downsample ID in stdout

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by beatrizsavinhas** [comment]
I had some notes on the current downsampling process that might be useful here:

* keep case name matching original

* update reads on status DB so that fastq files can be uploaded automatically

* generate delivery reports https://github.com/Clinical-Genomics/cg/issues/1842

**Comment by fevac** [comment]
Very good points!  

Regarding the first one, do you mean keeping same case name and creating new case ID? What about sample names, should they also be the same?

For testing purposes I think we often want to have new case names since we will want to treat the downsampled cases as independent cases and view them independently in scout.

I would also be cautious of giving same names unless there is a good reason for it, what is the idea behind it?

**Comment by Vince-janv** [comment]
If I'm not mistaken @karlnyr has been working on this on and off for a while. I suggest we wait with the refinement until he is back.

**Comment by fevac** [comment]
Decision: 
- Using new case names

**Comment by beatrizsavinhas** [comment]
Yeah, sorry for not specifying better before. I meant automatically create a case name that matches the original but not the same, p. e. `case_downsampled` or `orginalcasename-numberofdownsampledreads`. This is because the current downsampling process generates the case name based on the case id of the original case (p.e. downsampled case name = original_petname-40M) and the customers could not easily identify which original case the downsampled one referred to.

**Comment by ChrOertlin** [comment]
# Implementation plan

A sample should always be associated to a case. In some instances we would want to down sample distinct samples under a case to a different final read count.

## Implementation of CLI cmds:

### `cg down-sample sample -c <case_internal_id> -s <sample_internal_id>;<reads> -s <sample_internal_id>;<reads>`

It will then: 
- create a new case in statusDB called `<case_internal_id>_DS` 
- for each sample create a new sample in statusDB called '<sample_internal_id>_<reads>M'
- for each sample create a link to the specified case under `<case_internal_id>_DS` 
- for each sample specified under '-s' it will down sample the sample to the specified '<reads>' number

### `cg down-sample case -c <case_internal_id> -r <reads>`
This command take a case (specified by -c) and a reads number (specified by -r)
It will then:
- create a new case in statusDB called `<case_internal_id>_DS` 
- for each sample create a new sample in statusDB called '<sample_internal_id>_<reads>M'
- for each down sampled sample create a link to `<case_internal_id>_DS` 
- for each sample specified under '-s' it will down sample the sample to the specified '<reads>' number
 

#### Both flows will include the following
##### Input checks
- Do the specified case and samples exist - if not raise an error and abort
- Do the specified samples have a number of reads that exceed the specified final read count - if not raise an error and abort

##### Down sample flow
- Check if the specified samples require 'decompression' 
- If 'decompression` is needed, start decompression, notify the user and exit.
- Create new case and sample entries in statusDB
- Start a `down sample` workflow that can be tracked by `Trailblazer`
- Once the `down sample` workflow is done add the newly created fastq files into housekeeper

**Comment by fevac** [comment]
Nice. Some personal preferences:
- Call it `cg downsample` without `-`
- Case naming: I would avoid calling the new case `<case_internal_id>_DS`. I think this could lead to several cases having case name (if the same case is downsampled several times). If we are ok with duplicated case names, I would still change _DS to _downsampled or similar (but written so anybody would understand). Alternatively we could require a new case name to be provided. 
- Sample naming: I guess you mean `<sample_internal_id>_<million_reads>M`
- As I mentioned of Friday, I also rather have samples and reads provided separately in order, by I think I'm outnumbered. E.g. `--samples SAMPLE1,SAMPLE2 --reads READSFORSAMPLE1,READSFORSAMPLE2`

I was also thinking that you can give either all information:
`cg downsample sample --analysis <analysis> --delivery <delivery> --ticket <ticket_number> --customer <customer> --case-name <new_case_name> --samples <samples> --reads <reads>`

Or transfer information:
`cg downsample sample --transfer_from_case <original_case>  --samples <samples> --reads <reads>`


 As for the input checks:
 `Do the specified samples have a number of reads that exceed the specified final read count - if not raise an error and abort` --> I think you might want to have the option to keep the original sample in that case. Like if a case have several samples and one of them has less reads than aimed for, you might want to downsample all others and keep the original sample when it doesn't exceed the amount of reads

**Comment by ChrOertlin** [comment]
"_Call it cg downsample without -_"
I will change it to downsample. 😭 

_"Case naming: I would avoid calling the new case <case_internal_id>_DS. I think this could lead to several cases having case name (if the same case is downsampled several times). If we are ok with duplicated case names, I would still change _DS to _downsampled or similar (but written so anybody would understand). Alternatively we could require a new case name to be provided."_

I think this is a problem that is solved by itself. A case will always get a "new" internal id. It seems like that when one uses `status_db.add_case` a new pet name is generated. 

I will change `_DS` to `down_sampled` though.


"_Sample naming: I guess you mean <sample_internal_id>_<million_reads>M_"

Indeed, as user you just provide the reads in millions, i.e. 30 if you want to down sample to 30_000_000. The rest will be handled internally.

"_As I mentioned on Friday, I also rather have samples and reads provided separately in order, by I think I'm outnumbered. E.g. --samples SAMPLE1,SAMPLE2 --reads READSFORSAMPLE1,READSFORSAMPLE2_"

I think having them paired like `sample;reads` makes it less error prone for the user and implementation wise it is also a bit easier since you don't need to juggle with list indeces.


"_I was also thinking that you can give either all information:
cg downsample sample --analysis <analysis> --delivery <delivery> --ticket <ticket_number> --customer <customer> --case-name <new_case_name> --samples <samples> --reads <reads>

Or transfer information:
cg downsample sample --transfer_from_case <original_case>  --samples <samples> --reads <reads>_"

The latter one is standard behaviour. It will always take the information given from the case linked to the provided case_internal_id. 

We can for sure implement that users can provide these attributes and build a case around that.


"_As for the input checks:
Do the specified samples have a number of reads that exceed the specified final read count - if not raise an error and abort --> I think you might want to have the option to keep the original sample in that case. Like if a case have several samples and one of them has less reads than aimed for, you might want to downsample all others and keep the original sample when it doesn't exceed the amount of reads_"

I think the down sample api should not be able to make that decision. It should down sample what is given as input if that is possible. If not the user has to change the input and link the un-touched samples outside of the API. This is my opinion though, if there is a reason to have this in there we can for sure implement it.

**Comment by fevac** [comment]
- "I will change _DS to down_sampled though." --> To `_downsampled` ? 

- "We can for sure implement that users can provide these attributes and build a case around that." -> I think having that option would be great. I would use this when downsampling mip cases to rnafusion cases for example. 

- "I think the down sample api should not be able to make that decision. It should down sample what is given as input if that is possible. If not the user has to change the input and link the un-touched samples outside of the API. This is my opinion though, if there is a reason to have this in there we can for sure implement it."  -> I think you can abort by default, but having an option to only downsample available could be good. This could be implemented later though. What you think @karlnyr ?

**Comment by karlnyr** [comment]
I think that the number of times that a case includes a sample, where a subset has less than the required reads, we should simply skip that sample (equal to not including it in the new downsampled case) or include it but not downsample it. the number of times this will happen is going to be very few - so as long as we are somehow informed that one sample does not have enough reads it would be fine.

**Comment by ChrOertlin** [comment]
Resolved by: #2488
