### ISSUE TITLE
Inconsistent values for q30 metrics

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2350]
## Description
In the sequencing metrics table, we have inconsistent data in the column called `sample_base_fraction_passing_q30`. Most of the entries are reported as percentages, but all new ones are reported as fractions. The discrepancy arose due to the q30 scores ported from cgstats being stored as percentages.

## Suggested solution
Store the new q30 scores as percentages as well and transform existing fractions to percentages.

1. Create revision renaming the column to `sample_base_percentage_passing_q30` or maybe just `base_percentage_passing_q30`.
2. Update logic to populate the column with percentages instead of fractions.
3. Update NIP q30 threshold to percentage.
4. Update q30 filtering in store.
5. Update lims usage of metrics.
6. Transform existing fractions to percentages.

## This can be closed when
- The q30 scores are stored and used assuming a single format

**Comment by seallard** [comment]
Given that there might be current and future dependencies on this value assuming it is reported as a percentage, maybe the least invasive/error prone approach would be to store it as a percentage. What do you think?

**Comment by ChrOertlin** [comment]
From what I see we use the bases passing QC in the following places:
cg/apps/sequencing_metrics_parser/parsers/bcl_convert.py - parses the q30 values directly from file which are in fractions
cg/constants/sequencing.py - Enum class where Q30thresholds are stored as INTs (i.e. percentages)
cg/store/filters/status_metrics_filters.py - Checking if somehting passes a q30 thresholds, takes the sequencing constants above and converts them to fractions
cg/constants/nipt.py - Constant Q30 threshold stored as fraction

We use the Q30_THRESHOLD to determine whether a flow cell should be stored in CGstats currently and in NIPT to check whether to upload. Is this right @karlnyr 

# approach 1

1. Transform all fractions to percentages in SampleLaneSequencingMetrics
2. Change the column name in the SampleLaneSequencingMetrics table to display percentage
3. Transfrom the  parsed fractions %Q30 in cg/apps/sequencing_metrics_parser/parsers/bcl_convert.py to percentages (possibly also %Q30 in cg/apps/sequencing_metrics_parser/parsers/bcl_convert.py)
4. Alter the cg/store/filters/status_metrics_filters.py  to not transform the Q30 threshold used therein
5. Alter the NIPT Q30 Threshold from fraction to percentage cg/constants/nipt.py 

# approach 2: 

1. When CGstats is deprecated alter cg/constants/sequencing.py  to fractions
2. When CGstats is deprecated alter the cg/store/filters/status_metrics_filters.py  to not transform the Q30 threshold used therein
3. Transform all percentages to fractions in SampleLaneSequencingMetrics

I would go for the way of least resistance. Assuming we only use the Q30 threshold in the capacity identified above that would be approach 2 (i.e. using fractions). 

Otherwise I have no preference in using a float over an int.

# Example old flow cell copied from cgstats with percentages

https://files.slack.com/files-pri/T02HT5X58-F05NGRY8VGC/image.png

# Example flow cell processed in new flow with fractions

![image](https://github.com/Clinical-Genomics/cg/assets/8860786/015e48ef-b422-4c81-a404-c10659f3b2e8)

**Comment by karlnyr** [comment]
All I know is that we use Q30 in two places - when parsing the output of a flow cell and when we upload nipt analyses to Statina.

**Comment by ChrOertlin** [comment]
@karlnyr, indeed that is what I thought as well. I also cannot find any other place in the code relying on a Q30 threshold.

**Comment by seallard** [comment]
We are also using it in lims

**Comment by seallard** [comment]
> I think the difference in work for the both approaches are quite small, and that being the case i think just porting the Unaligned table from cgstats to cg is safest, meaning I think we should keep percentages.

I agree, I'll expand on the implementation plan of @ChrOertlin

**Comment by ChrOertlin** [comment]
Sounds like a plan! Percentages it is! :) The implementation plan looks good.
