### ISSUE TITLE
Sync fastq files from thalamus to hasta (2500 and novaseq data)

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#243]
As a production team member, I would like to get fastq files form thalamus deliverd to hasta so that I can deliver fastq files to customers and start analysis.

Problem: fastq files are now sent to rasta

Suggested solution:
- thalamus:
  - add a crontab that sends data to hasta. Copy the line that sends data to rasta and make a new one that now send to hasta. OK, might not be that easy as only one of those crontabs will execute and then block the other one. Suggestions? --> let 2nd script check for copycomplete-hasta.txt? Also, there's a program called ```pssh``` that can sync to multiple servers.

Questions:
Q: where do fastq files reside on hasta?
A: `/home/proj/demultiplexed-runs`
Q: "might not be that easy as only one of those crontabs will execute and then block the other one". Why does this happen?
A: because copycomplete.txt is created during first copy.
Q: Suggestions?
A: Let 2nd script check for copycomplete-hasta.txt?

DoD:
- show that hasta has fastq files sent from thalamus
- documentation: 1160 in AM

**Comment by barrystokman** [comment]
Prerefined 21081206

**Comment by emiliaol** [comment]
Related question in a way, all ssh connections are set up with casear, thalamus, clinical-db and so on? So that we in theory could move the delivery of raw data to hasta already now (after installing delivery and what more?). Or to reformulate my question: What do we need installed/set up on Hasta to be able to do raw data delivery from there? And what of that is already in place?

**Comment by patrikgrenfeldt** [comment]
It seems to me that pssh is a suite of tools and in that suite is prsync that can transfer files to multiple hosts, see https://www.tecmint.com/copy-files-to-multiple-linux-servers/
