### ISSUE TITLE
mapped_reads as property

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/cg#2744]
maybe we can make `mapped_reads` a property on `sample_metrics` that does the caluclation and you can call `sample_metrics.mapped_reads` here instead. Would make the code more readable and understandable.

_Originally posted by @ChrOertlin in https://github.com/Clinical-Genomics/cg/pull/2621#discussion_r1418973383_

**Comment by fevac** [comment]
@ivadym are you on board with this suggestion? I don't want to spend time on this if not needed

**Comment by ivadym** [comment]
It's a good point, but I wouldn't mix `RnafusionQCMetrics` and `RnafusionSampleMetadataModel` metrics. They have clearly different purposes. The first one is the model for extracting the raw QC metrics that the pipeline produces, while the second one is the model that feeds the delivery report. We should either merge them together (not straightforward since in `RnafusionSampleMetadataModel` we have data from LIMS for example) or keep them independent. A partial solution with some metrics logic here and some there doesn't seem like a good idea to me

**Comment by fevac** [comment]
Got it. Closing then
