### ISSUE TITLE
CLI command cg add sample generates sample with missing information for Original Ticket which later prevents case upload

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#2962]
## Description

A sample created with the following command:

`cg add sample -l SAMPLE_LIMS_ID -o ORDER -s SEX -a APPTAG -p research CUST_ID SAMPLE_NAME`

is created in statusDB but misses information in the field `Original Ticket`.

When the analysis for a case that contains this sample is complete, the upload fails with the following error:
```shell
Could not generate report data for CASE. Missing data:
samples:
  SAMPLE:
  - ticket
```

## Suggested solution

3 possible solutions:

- Add option in the `cg add sample` command to specify `Original Ticket`;
- Inherit `Original Ticket` from the given order in `cg add sample`;
- Make upload independent of the information on `Original Ticket`.

## This can be closed when

An analysis for a sample created with the `cg add sample` command can be uploaded with no errors.

## Blocked by

Nothing.

**Comment by henrikstranneheim** [comment]
Added to refinement: 2024-02-21

**Comment by Vince-janv** [comment]
### Decision:
Since original_ticket is necessary for a case to upload successfully one should be forced to pass it as an argument in the cli command that adds a sample.

The method `cg.store.crud.create.CreateHandler.add_sample` already has an original_ticket parameter so all that is needed is to add a click.option to `cg.cli.add.add_sample` which should be mandatory to pass.
