### ISSUE TITLE
Newly started microsalt analysis displayed as completed before finishing

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2966]
## Description
Re-started a case with this command cg workflow `microsalt start <case_id>`, and it showed up in TB as pending and then completed before the command finished.

![image](https://github.com/Clinical-Genomics/cg/assets/33596072/0023cdcf-c6b4-4e86-a860-948d5a649432)

**Comment by seallard** [comment]
When looking at the data, it seems like the jobs from the previous failed analysis somehow show up as the jobs for the restarted analysis.

**Comment by islean** [comment]
The screenshot's resolution is a bit grainy. Can't really see what it says...

**Comment by islean** [comment]
But also, it needs to be anonymized.

**Comment by seallard** [comment]
> But also, it needs to be anonymized.

We really need to make this repo private, reporting bugs in a meaningful way is impossible now

**Comment by islean** [comment]
> > But also, it needs to be anonymized.
> 
> We really need to make this repo private, reporting bugs in a meaningful way is impossible now

That should indeed be done, but as is, we are stuck with anonymizing data.

**Comment by Vince-janv** [comment]
### Hypothesis:
1. MicroSALT writes the slurm_ids file when it is completed. In this case 30 min after start. 
2. The config_path column for the two analyses in trailblazer for shiningvervet point to the same path. 
3. The slurm_ids file from the first microSALT analysis is still there.
4. Trailblazer scan is run before the second analysis overwrites the slurm_ids file of the first.
5.  Trailblazer will then parse all the old jobs and set the status to completed since those are done.

**Comment by seallard** [comment]
Yes, that is correct. Looking at the analysis entries for the case - the paths are identical and they point to the same `/home/proj/production/microbial/results/reports/trailblazer/<project_id>_slurm_ids.yaml`.

As for point one, microsalt writes the file before.
