### ISSUE TITLE
Relationships are not added when downsampling a case.

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/cg#3052]
## Description

When doing `cg downsample samples` on a case, e.g. a trio in mip-dna, relationships are not propagated (maternal id and paternal id), and have to be re-added manually.

## Suggested solution

A suggested solution would be to have the command add the relationships as present in the original case.

## This can be closed when

This can be closed when the relationships are added upon running the suite of `cg downsample` commands.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by peterpru** [comment]
That is a good point. It would ideally be propagated when downsampling a trio. I.e. I used the command to downsample the trio all at the same time, and store them in a new case. But if someone downsamples only a single sample, then there is no need to keep the relationships for that new case, or to automatically add the parents.

**Comment by Vince-janv** [comment]
### Description clarification
Downsampling is the act of removing reads randomly and at CG we create a new sample entry as well as a new housekeeper bundle for it. The command `cg downsample samples` downsamples the samples and creates a new case to link the new samples to. The relationships between the samples in the old case is not duplicated.

**Comment by Vince-janv** [comment]
### Technical refinement
The way the command is designed this it allows adding samples not necessarily in the same case originally. This makes a mirroring of relationships from the old case difficult.

### Decision
This command is used so seldomly that running two extra CLI commands to relate samples to each other is acceptable

### Actions
- Clarify help message of `cg downsample samples` to not say that all case info is transferred
- Add to the message above that one needs to run cg add relationship in order to get mother/father and status
