### ISSUE TITLE
Gens not available for some cases

### ISSUE THREAD

**Issue by ElekCMMS** [Clinical-Genomics/cg#3314]
Hi,

For case **15126** and **15006-quattro** I'm not able to access GENS in the structural variant page. Other users have tried with these cases as well without sucess and other cases works fine for me.

I get the following message when clicking on Gens:
![Skärmklipp](https://github.com/Clinical-Genomics/scout/assets/171581890/796dcf45-9de8-45ec-90d1-1b642bf0e66f)

Thank you!

**Comment by ElekCMMS** [comment]
Hi! There is no hurry with these samples, thank you for the update!

**Comment by Vince-janv** [comment]
# To be refined in separate meeting
@seallard will prepare and distribute info before meeting

**Comment by seallard** [comment]
The observed bug is due to gens attempting to load files which do not exist - a re-run has been done for the case and the old files have been deleted, but gens has not been updated with the new file paths.

More worryingly, this bug only appeared due to the old files for the previous run having been deleted. Otherwise, the users would have seen the old data without knowledge of it being an older run. How bad is that?

Given that the tool seems to present meta data related to the raw sequencing data (such as sequencing depth), I assume that this is not too critical since a re-run (to my knowledge) usually does not involve re-sequencing and the underlying raw sequencing data should be the same. If this is not the case, the issue might be really bad - potentially misleading the person interpreting the data.

**Comment by Vince-janv** [comment]
Solved by https://github.com/Clinical-Genomics/cg/pull/3389. Running `cg upload gens <case_id>` (which is invoked in the upload command) now overwrites previous entries in the gens database.

The two cases mentioned in the issue have been re-uploaded
