### ISSUE TITLE
Bug: OrderIn classmethod parse_object

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#3939]
```
  @classmethod
    def parse_obj(cls, obj: dict, project: OrderType) -> "OrderIn":
        parsed_obj: OrderIn = super().parse_obj(obj)
        parsed_obj.parse_samples(project=project)
        parsed_obj.order_type = project
        return parsed_obj
```

This code overrides the internal Pydantic method and seem to be used to determine the order type and validate the correct order model in a very hard to understand way - hard linked to the Pydantic version. Making it a very unmaintainable piece of code preventing updates and extensions.

**To Reproduce**
1. Try to update Pydantic or change the name of the class method

**Expected behavior**
Update Pydantic without having to override Pydantic internal methods.

**Additional context**
The FE should know what type of order is being submitted and include it in the submission so the BE can choose the correct model to validate and use.

**Comment by islean** [comment]
> @Vince-janv @islean What is your take on this?

I do not like the OrderIn objects because they are hard to understand (on top of the Pydantic versioning compatability), and a lot of the functionality they provide is being deprecated in the improve-order-flow project now. Could we finish integrating the new validation services and come back to this? If we are lucky, we might be able to remove all OrderIn classes 🤞

**Comment by henrikstranneheim** [comment]
Sounds good! Let's revisit once it is finished.
