### ISSUE TITLE
cg get sample output quite tricky to parse properly

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#398]
As a busy person, I want to get family name for samples without multiple pipes to cleanup tabulated SQL output in https://github.com/Clinical-Genomics/cg/blob/master/cg/cli/get.py

Problem: 
cg get sample prints out a non parse friendly output using tabulate. Jut to get family name one has to use multiple unnecessary and messy bash pipe.

Steps to reproduce
  1. cg get sample --families ACCXXXX

Expected outcome / suggested solution:
cg get sample --families to print something less pretty but more useful.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by ingkebil** [comment]
That is intentional. All these functions are not supposed to be used in bash scripts and are only intended for usage by humans. If you want to get information from statusdb or connect statusdb with other tools, you do that through `cg`. (usually in a `cg/api/name_of_your_tool.py` or `cg/meta/name_of_the api_that_connects_multiple_tools.py`.

Reason: we don't want to run a systems test everytime we are changing the output of a command. Especially if we don't know what other commands might be consuming the output.

**Comment by hassanfa** [comment]
I understand your point of view, and it makes sense. I was looking for a way to bring balsamic closer to production by introducing how one would start from a sample name and end up running the workflow.

You mentioned api/meta: How these api/meta tools should behave? They won't be part of CLI I suppose, right?

I have a proposal, the output is tabulated SQL-like table. Would it make sense if I look into providing an option: `--json` which provides a json format instead of tabulated one? How hard/easy would it be to implement it? (PS: I am aware adding more options means more work on mocks and unit tests.)

**Comment by ingkebil** [comment]
> I understand your point of view, and it makes sense. I was looking for a way to bring balsamic closer to production by introducing how one would start from a sample name and end up running the workflow.
> 
> You mentioned api/meta: How these api/meta tools should behave? They won't be part of CLI I suppose, right?

I don't 100% understand what you're saying here, so forgive me if I'm answering next to the point.

So far, an api has been a mapping from all python functions from a tool (e.g. housekeeper) that are used anywhere in cg. As in: any function or class you want to import from housekeeper, you _only_ import in the api. cg itself will then _only_ use the api to connect to housekeeper. If any of the imported functions or classes changes, we quickly notice, as the unit tests will fail on changed function signatures. (yay!)
We quickly ran into the problem that well, one forgets to add the functions one's using in cg to the api. The way forward is to use the tool's cli and interact with the tool through the cli and never import any python. Again, one would add this functionality to the api and then only use the api anywhere else in cg. This can be seen with loqus: https://github.com/Clinical-Genomics/cg/blob/master/cg/apps/loqus.py

Depending on their use, they will or won't be part of cg's cli. loqus for example, is used in `cg analysis upload` if I remember correctly.

> I have a proposal, the output is tabulated SQL-like table. Would it make sense if I look into providing an option: `--json` which provides a json format instead of tabulated one? How hard/easy would it be to implement it? (PS: I am aware adding more options means more work on mocks and unit tests.)

This has been proposed before and I have always said no. Reason: nobody ever comes back to fix this or the fix is pushed way down on one's todo. Anyway, let's say yes this time. Feel free to implement this.

**Comment by hassanfa** [comment]
Alright, I'll look into it and draft a PR.

**Comment by ingkebil** [comment]
Btw, @patrikgrenfeldt  is back from holidays and he could help you navigate the solution using the api and meta apis instead! Just hit him up :)

**Comment by patrikgrenfeldt** [comment]
Yes I'm back :) and I would love to see a new command in CG 'cg start balsamic ...', I suggest you create a pull request on that instead and get all the info you need directly at the source :) what do you say about that?

**Comment by hassanfa** [comment]
This is my toy project to learn about CG. A 30 min per week toy project 🙃. And this feels like a quick fix as well.

The one you mentioned requires sacrificing my current priorities and allocating more time that I have.

**Comment by patrikgrenfeldt** [comment]
Please feel free to get inspiration from the templates from https://en.wikipedia.org/wiki/User_story#Common_templates and add the WHY/BENEFIT part so we can minimize the risk of the [XY-problem](https://en.wikipedia.org/wiki/XY_problem)

**Comment by hassanfa** [comment]
Isn't it there already? 😄 Ok let's close this issue. I'll use a different approach.
