### ISSUE TITLE
CGH files created by MIP are renamed with customer sample name before being uploaded to Scout

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#426]
As a user of Scout I want to be able to download the CGH file containing samples named with my sample name so that I understand which sample is which.

Problem: 
The CGH file is named with the cg internal id both on case and sample level. This needs to be processed before uploading to Scout so that the naming is external. 

Steps to reproduce

Expected outcome / suggested solution:

Questions: 
Q: Can MIP do this?
A: Nope. Discussed in Clinical-Genomics/cg#200 

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by dnil** [comment]
Thanks! I just had a colleague at cust002 notice the issue.. :)

**Comment by dnil** [comment]
..and we have now had the first missed diagnosis because of this. The manual relabelling in Cytosure failed due to a manual error but for highly similar sample file names. As a consequence an 8 Mb deletion was missed. It would enhance patient safety if we could get external customer IDs into the downloaded files.

**Comment by emiliaol** [comment]
I will bump it on the list so we can make the risk of this happening again smaller.

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt @emiliaol let’s take a look tomorrow. A quick fix to this is to supply the customer id in the pedigree file to MIP and then I can take it from there.

**Comment by patrikgrenfeldt** [comment]
@dnil In scout we see the customers sample name on the row of the individual:
![image](https://user-images.githubusercontent.com/6697636/74017180-0d93d100-4994-11ea-9f21-29d8da173bc2.png)

Downloaded file seems to have the customers sample name in the filename:
![image](https://user-images.githubusercontent.com/6697636/74017274-42078d00-4994-11ea-9e7d-dbbdf62d2cb4.png)

A grep of the internal sample id gave no hits in the cgh-file:
![image](https://user-images.githubusercontent.com/6697636/74017399-7aa76680-4994-11ea-95e2-2c2846f856fb.png)

Could you post a (non-sensitive) screenshot showing what needs to be changed?

**Comment by dnil** [comment]
The sample id is found in the CGH XML-ish sample tag option sampleId. It is currently set to a petname.
``` <sample sampleId="tenderoriole" male="false">```
 The latter I believe is parsed from the filename by vcf2cytosure. That was sort of the best we could do when no internal ids were available in MIP. It was helped somewhat by renaming the files from scout, but not enough unfortunately.
Either rename/relink the file before running vcf2cytosure, or we could add an option to vcf2cytosure that takes the desired sample id. Adding a few more descriptors would go well in the ```submission``` tag, e.g. replacing the ```dummy.cgh``` with the future actual filename.

**Comment by henrikstranneheim** [comment]
@dnil and @J35P312 Alright, I see several ways of doing this:
1. Since vcf2cytosure is parsing the vcf file, it seems more correct to pick the sample name from the vcf header #CHROM line and put that in the `sampleId="sample_id_from_vcf"` and not from the filename. I can create a process to rename the Clinical Genomics internal id to the customer sample name in the vcf going into vcf2cytosure. To me this seems like the best solution, where we follow standard formats and it is clear where the information is encoded.
2. I can simply rename the vcf to `customer_name_id.vcf`, but I think this assumes a lot about the filename and is more error-prone (evident by this issue...)

What do you think?

**Comment by dnil** [comment]
Sure, it should be simple to get the name from the vcf. Since the file name is to be read by computer, and only for one run, I don't think it actually matters much. One can also replace the "dummy.cgh" string in the file with the customer sample name later, if you still wish to keep this out of MIP.

**Comment by henrikstranneheim** [comment]
I will put it in MIP as this only affects the internal of the file and not the filename, meaning that this change will only be handled at the customer end-point, and to all other system it will look the same. This is contained to a very specific process end-process in MIP and only affecting the vcf2cytosure recipe.

Great I will go ahead according to 1. Let me know when there is a new vcf2cytosure version that can extract the sample_id from the vcf header

**Comment by dnil** [comment]
Ok, a release 0.5.1 is now available on GitHub. If you want to pull it from the sample Singularity hub as before, ping @J35P312 to add a singularity file and update/pull to his repo.  :smile:

**Comment by henrikstranneheim** [comment]
@J35P312 a singularity image would be great.

**Comment by J35P312** [comment]
Nicely done!
Daniel, could you draft a new vcf2cytosure release and update the singularity config?
I do not have permission to edit the NBIS repository =P

**Comment by dnil** [comment]
Ah, that's why! 😊 Ping Marcel / NBIS about that perhaps? Sure thing though! There was a branch already, but I've snuck a new singularity config into the master. We should look into generalising that at some point..

**Comment by J35P312** [comment]
Thanks! Now I have queued the container on singularity, it should be done in 30 min our so!

I like our system, it reminds med of Kafka!

**Comment by dnil** [comment]
Self-referential, decentralised and highly interconnected. I would not be totally surprised if it has a consciousness of its own!

**Comment by henrikstranneheim** [comment]
😄 
![Screenshot 2020-02-07 at 15 43 24](https://user-images.githubusercontent.com/584738/74038558-bb1cd980-49c0-11ea-8bf1-e60301ac31a8.png)

Any news on that image, all other code is done - just need a fresh vcf2cytosure

**Comment by J35P312** [comment]
Sorry for the delay! now it is finnished!

**Comment by henrikstranneheim** [comment]
Tested and it works great! Will merge this to mip 8.2 currently being validated in https://github.com/Clinical-Genomics/cg/pull/542

**Comment by henrikstranneheim** [comment]
Done #542
