### ISSUE TITLE
Not all fastq files in Housekeeper are linked with cg workflow mip-dna link

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cg#580]
As a member of bioinfo production I want all fastq files connected to a sample to be linked when starting the MIP analysis. 

Problem: 
`cg workflow mip-dna link` gives the destination path the same name which results in that not all fastq files in Housekeeper are linked. See attached picture for problem with the command `cg workflow mip-dna link -c ontahr`. 

Steps to reproduce
  1. Run the command `cg --log-level DEBUG workflow mip-dna link -c ontahr`
  2. Only two of eight fastq files are linked. 

Expected outcome / suggested solution:
All fastq files that are available in Housekeeper for a sample should be linked.

Questions: 
Q: Does the same problem occur for tea?
A: This is a known problem to us in bioinfo production but it doesn't occur very often, maybe it's connected to older externally sequenced samples as in this case?

![Screenshot 2020-03-04 at 13 33 16](https://user-images.githubusercontent.com/19236050/75880148-08a03100-5e1d-11ea-9693-9a42b85596ab.png)

**Comment by Mropat** [comment]
This has been fixed

**Comment by moonso** [comment]
Could you reference where this was fixed (PR) or explain the solution @Mropat ?

**Comment by Mropat** [comment]
ontahr  and its samples in ClinicalDB
![image](https://user-images.githubusercontent.com/35531751/98213587-9486d180-1f45-11eb-9ba3-6aa8742b32f7.png)

Fastq files in HK
![image](https://user-images.githubusercontent.com/35531751/98213805-ec253d00-1f45-11eb-8bc3-41c52c1826fc.png)
Due to strange naming convention of those files, cg link name parsing function will rename the files in a way that's not unique. 

This was an edge-case that was solved by linking files manually,  case analyzed and delivered
![image](https://user-images.githubusercontent.com/35531751/98214327-a3ba4f00-1f46-11eb-879f-9cd8cd00f71a.png)

The files come from a very old ticket
![image](https://user-images.githubusercontent.com/35531751/98214856-512d6280-1f47-11eb-9708-edb848a0c218.png)

The sample in question was never sequenced at cg and files were received with this naming pattern

**Comment by moonso** [comment]
Perfect! Good to know when this happens again
