### ISSUE TITLE
Custom cli options for workflows based on analysis and order context

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#785]
A bit broad title, but hear me out.

BALSAMIC, and workflows in general, have complex procedures to provide a correct and reliable result. To be able to do this, `cg` has to provide correct parameters to the workflow. This is also tightly related to what we deliver.

Case 1: `mutect2` is a somatic variant caller that won't perform well in some analysis due to high or low coverage, and will stall forever. `cg` should be able to instruct `balsamic` to disable mutect2 for some cases such as WES.

Case 2: For some whole genome applications we might not use `dragen` for variant calling, e.g. research cases that are not mission critical.

Case 3: Study design, e.g. utilizing UMI for filtering out variants. So `cg` should instruct `balsamic` based on order, study design, and context.

Case 4: Disable items of the workflow for some specific applications. e.g. disable a specific variant caller for WES or TGA analysis.

@Mropat and I briefly talked about this, and it sounds doable. For now we'd like to try out with disabling a specific variant caller in BALSAMIC. This can either go into a BALSAMIC specific constants, or we can define a study design model in `cg`.

Maria, what say you?

**Comment by hassanfa** [comment]
Further comment: This is very similar to provide tumor or tumor-normal BALSAMIC. It is a similar type of logic.

**Comment by Mropat** [comment]
I think if production needs this and uses this routinely, it is worth implementing. The way I would do it is not by adding every option in Balsamic to cg workflow balsamic, because this is how we revert back to having way too many options again. Perhaps we can have an option to add custom string to process call without declaring every option? 

But, by giving the end user the opportunity to send magic commands to pipelines adds complexity and leaves more room to make mistakes. On the other hand we can flexibly remove the need for production to ever use the pipline cli directly, and only use cg for everything.

**Comment by hassanfa** [comment]
We should avoid sending magic commands to process call, and we should certainly avoid making cg aware of every single balsamic cli option.

Instead we should have balsamic cli options in process call given the context. As we discussed briefly before, example is to disable Mutect2 for all whole exome applications or those TGA panels with very high coverage >4000x (this can be estimated from application tag already). Mutect2 is going to fail or stall; there is nothing we can do about it.

Example for Mutect2 is for routine analysis, and all routine analysis should be automated as much as possible.

**Comment by hassanfa** [comment]
Stale. Closing.
