### ISSUE TITLE
cg balsamic delivery command issue 

### ISSUE THREAD

**Issue by ashwini06** [Clinical-Genomics/cg#900]
**Problem:** 
The wrong folder 'G1A1440p44' is copied to other case folders with the cg deliver command

Steps to reproduce:
`cg deliver analysis -c funnyslug -d balsamic`
`cg deliver analysis -c amusedskink -d balsamic`
`cg deliver analysis -c oneel -d balsamic`
`cg deliver analysis -c decentcougar -d balsamic`

`ls /home/proj/production/customers/cust059/inbox/215172/*`

<img width="557" alt="Screenshot 2020-12-17 at 13 31 57" src="https://user-images.githubusercontent.com/6302819/102488466-5e705d80-406c-11eb-9e4b-f18524182739.png">

**Comment by moonso** [comment]
Could you elaborate a little. What is expected and what is wrong here?

**Comment by ashwini06** [comment]
**Scenerio:** 

Balsamic analysis is done for the following cases and the data needs to be delivered (vcf, fastq, bam) to the caesar
```
equalkoi - ACC7204A1
civilsole - ACC7204A2
cleverdoe - ACC7204A3
bigox - ACC7204A4
funnyslug - ACC7204A5 (T) + ACC7204A3 (N)
amusedskink - ACC7204A6 (T) + ACC7204A3 (N)
oneel - ACC7204A7 (T) + ACC7204A3 (N)
decentcougar - ACC7204A8 (T) + ACC7204A3 (N)
```

Here `ACC7204A3` (G1A1440p44) is a normal sample and is used for multiple cases. And the total raw data folder size for this sample `ACC7204A3` is 125G. If the same data folder is copied multiple times to each individual case folder, it requires a bigger storage space for the customer on caesar.

I expect that the G1A1440p44 raw data folder should be copied only once to 

/home/proj/production/customers/cust059/inbox/215172/**G1A1440p44**_Balsamic/**G1A1440p44**  

SkIp for the rest of the cases if raw data folder exists in its main folder (i.e. G1A1440p44_Balsamic)

/home/proj/production/customers/cust059/inbox/215172/G1A144088p7_Balsamic/**G1A1440p44** 
/home/proj/production/customers/cust059/inbox/215172/G1A144090p6_Balsamic/**G1A1440p44**
/home/proj/production/customers/cust059/inbox/215172/G1A144086p9_Balsamic/**G1A1440p44**
/home/proj/production/customers/cust059/inbox/215172/G1A144087p5_Balsamic/**G1A1440p44**

**Comment by moonso** [comment]
Hi @ashwini06 , this has not been part of the discussions when we designed the delivery script. Luckily the files are not copied but [hard linked](https://www.geeksforgeeks.org/soft-hard-links-unixlinux/) so that the file exists in multiple directories does not mean that it occupies more space on disc. 
However when syncing to ceasar I assume that the data will be duplicated for each sample. Perhaps we could figure out if the r syncing needs to be improved or if it would be ok to do like this. While thinking about that I would suggest that you manually rsync in a way that the files are not duplicated.

On a side note, are you sure that you want to deliver those files. When talking to Keyvan it sounded like the customer rarely want the big files, that's why I implemented the other alternative called `cg deliver analysis -d balsamic-analysis`

**Comment by ashwini06** [comment]
@moonso if it is designed as such, no issues then! 

yes it was a request from the customer about the raw data files and keyvan also confirmed me which files to deliver.

**Comment by moonso** [comment]
Could we keep it like it is and if the problem seems to be recurring we can try to make a fix for it? Is that ok with you @ashwini06 ?

**Comment by ashwini06** [comment]
@moonso: Alright :)
